before_script:
  - npm update

lint:
  image: node:latest
  stage: build
  script:
    - npm run lint
  artifacts:
    expire_in: 1 week
    paths:
      - dist

build site:
  image: node:latest
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit test:
  image: node:latest
  stage: test
  script:
    - npm run test:unit